language: node_js
node_js:
  - "10"
cache:
  directories:
  - node_modules # NPM packages
branches:
  only:
  - master
before_script:
  - npm install `cat npm-requirements.txt`
script:
  - remark ./docs/ --frail
  - remark ./inputs/ --frail
